
CREATE TABLE "BOAGLIO1"."TESTE_DRIVER_OCI"
(
   UF varchar2(72),
   CIDADE varchar2(72),
   BAIRRO varchar2(72),
   ENDERECO_CEP varchar2(9),
   LOGRADOURO varchar2(72),
   ID decimal(22) PRIMARY KEY NOT NULL,
   ALTERACAO timestamp DEFAULT SYSDATE  NOT NULL,
   ID_CORRIDA decimal(22) NOT NULL
)
;
CREATE UNIQUE INDEX PK3 ON "BOAGLIO1"."TESTE_DRIVER_OCI"(ID)
;
CREATE TABLE "BOAGLIO1"."TESTE_DRIVER_THIN"
(
   UF varchar2(72),
   CIDADE varchar2(72),
   BAIRRO varchar2(72),
   ENDERECO_CEP varchar2(9),
   LOGRADOURO varchar2(72),
   ID decimal(22) PRIMARY KEY NOT NULL,
   ALTERACAO timestamp DEFAULT SYSDATE  NOT NULL,
   ID_CORRIDA decimal(22) NOT NULL
)
;
CREATE UNIQUE INDEX PK2 ON "BOAGLIO1"."TESTE_DRIVER_THIN"(ID)
;
CREATE TABLE "BOAGLIO1"."TESTE_JAVA_PROC"
(
   UF varchar2(72),
   CIDADE varchar2(72),
   BAIRRO varchar2(72),
   ENDERECO_CEP varchar2(9),
   LOGRADOURO varchar2(72),
   ID decimal(22) PRIMARY KEY NOT NULL,
   ALTERACAO timestamp DEFAULT SYSDATE  NOT NULL,
   ID_CORRIDA decimal(22) NOT NULL
)
;
CREATE UNIQUE INDEX PK4 ON "BOAGLIO1"."TESTE_JAVA_PROC"(ID)
;
CREATE TABLE "BOAGLIO1"."TESTE_PROCEDURE"
(
   UF varchar2(72),
   CIDADE varchar2(72),
   BAIRRO varchar2(72),
   ENDERECO_CEP varchar2(9),
   LOGRADOURO varchar2(72),
   ID decimal(22) PRIMARY KEY NOT NULL,
   ALTERACAO timestamp DEFAULT SYSDATE  NOT NULL,
   ID_CORRIDA decimal(22) NOT NULL
)
;
CREATE UNIQUE INDEX PK ON "BOAGLIO1"."TESTE_PROCEDURE"(ID)
;
